/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { 
  User, 
  School,
  Song, 
  TalentItem, 
  SchoolEvent, 
  CommunityPost, 
  Choir, 
  Podcast, 
  NotificationItem, 
  TalentVideo,
  AuditLog,
  PlatformSettings,
  ReportItem
} from '../types';

export const INITIAL_SCHOOL = {
  id: 'school-st-jude',
  name: 'St. Jude Creative Arts Academy',
  motto: 'Discover Talent. Create. Connect. Shine.',
  location: 'North Wing Campus',
  establishedYear: 1998,
};

export const INITIAL_SCHOOLS: School[] = [
  {
    id: 'school-st-jude',
    name: 'St. Jude Creative Arts Academy',
    code: 'STJ-ARTS-01',
    district: 'Metropolitan Unified Arts District 4',
    address: '450 Symphony Blvd',
    city: 'St. Jude',
    state: 'CA',
    studentCount: 1240,
    facultyCount: 86,
    capacity: 1500,
    status: 'active',
    principal: 'Dr. Sarah Vance',
    logoUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=200&auto=format&fit=crop&q=80',
    academicYear: '2025-2026',
    foundedYear: 1998
  },
  {
    id: 'school-metro-prep',
    name: 'Metropolitan Conservatory High',
    code: 'MCH-MUSIC-02',
    district: 'Metropolitan Unified Arts District 4',
    address: '120 Concerto Way',
    city: 'Metro City',
    state: 'CA',
    studentCount: 980,
    facultyCount: 72,
    capacity: 1100,
    status: 'active',
    principal: 'Prof. Arthur Pendelton',
    logoUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=200&auto=format&fit=crop&q=80',
    academicYear: '2025-2026',
    foundedYear: 2004
  },
  {
    id: 'school-lincoln-visual',
    name: 'Lincoln Digital & Performing Arts',
    code: 'LDPA-INNOV-03',
    district: 'Bay Area Creative Secondary',
    address: '880 Innovation Parkway',
    city: 'San Francisco',
    state: 'CA',
    studentCount: 1120,
    facultyCount: 78,
    capacity: 1300,
    status: 'active',
    principal: 'Dr. Evelyn Chen',
    logoUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=200&auto=format&fit=crop&q=80',
    academicYear: '2025-2026',
    foundedYear: 2012
  }
];

export const DEMO_USERS: User[] = [
  {
    id: 'user-superadmin',
    email: 'superadmin@vibra.edu',
    name: 'Marcus Thorne',
    username: 'superadmin_marcus',
    role: 'superadmin',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    schoolId: 'school-st-jude',
    schoolName: 'St. Jude Creative Arts Academy',
    grade: 'System Administration · Super Admin',
    bio: 'Vibra Central Platform Architect and Security Trustee. Oversees network schools and access control.',
    talents: ['Platform Architecture', 'Security Engineering', 'Database Governance'],
    followersCount: 1200,
    followingCount: 10,
    badges: ['Super Admin', 'Platform Creator'],
    status: 'active',
    password: 'SuperAdmin2026!',
    createdAt: '2022-01-01T00:00:00Z',
    lastLoginAt: '2026-09-30T02:30:00Z'
  },
  {
    id: 'user-admin-vance',
    email: 'principal.vance@stjude.edu',
    name: 'Dr. Sarah Vance',
    username: 'dr_sarah_vance',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    schoolId: 'school-st-jude',
    schoolName: 'St. Jude Creative Arts Academy',
    grade: 'Administration · Principal',
    bio: 'Principal & Executive Patron of School Cultural Life. Dedicated to fostering safe, vibrant student expression.',
    talents: ['School Administration', 'Curriculum Arts', 'Governance'],
    followersCount: 950,
    followingCount: 15,
    badges: ['Principal', 'Platform Admin'],
    status: 'active',
    password: 'AdminVance2026!',
    createdAt: '2022-06-01T09:00:00Z',
    lastLoginAt: '2026-09-29T14:10:00Z'
  },
  {
    id: 'user-teacher-sterling',
    email: 'd.sterling@stjude.edu',
    name: 'Mr. David Sterling',
    username: 'sterling_arts',
    role: 'teacher',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
    schoolId: 'school-st-jude',
    schoolName: 'St. Jude Creative Arts Academy',
    grade: 'Faculty · Head of Performing Arts',
    bio: 'Music Director & Faculty Patron for Student Talents. 14 years empowering student voices in choral and theatrical performance.',
    talents: ['Choir Conductor', 'Orchestration', 'Audition Reviewer'],
    followersCount: 680,
    followingCount: 42,
    badges: ['Faculty Patron', 'Music Director'],
    status: 'active',
    password: 'TeacherSterling!',
    createdAt: '2023-08-01T09:00:00Z',
    lastLoginAt: '2026-09-29T16:45:00Z'
  },
  {
    id: 'user-maya',
    email: 'maya.lin@stjude.edu',
    name: 'Maya Lin',
    username: 'mayalin_music',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    schoolId: 'school-st-jude',
    schoolName: 'St. Jude Creative Arts Academy',
    grade: 'Grade 11 · Junior',
    bio: 'Singer-songwriter, acoustic guitar & indie-pop producer. Vocalist for the Horizon Chamber Choir. 2025 Regional Solo Gold Winner.',
    talents: ['Vocalist', 'Guitarist', 'Music Production'],
    followersCount: 342,
    followingCount: 128,
    badges: ['Vocal Gold 2025', 'Featured Artist', 'Choir Lead'],
    status: 'active',
    password: 'StudentMaya2026!',
    createdAt: '2025-09-01T08:00:00Z',
    lastLoginAt: '2026-09-30T01:15:00Z'
  },
  {
    id: 'user-liam',
    email: 'liam.vance@stjude.edu',
    name: 'Liam Vance',
    username: 'liam_codes_art',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    schoolId: 'school-st-jude',
    schoolName: 'St. Jude Creative Arts Academy',
    grade: 'Grade 10 · Sophomore',
    bio: 'Creative technologist & digital illustrator. Building generative canvas shaders and digital installations.',
    talents: ['Creative Coding', 'Digital Art', 'Motion Design'],
    followersCount: 289,
    followingCount: 94,
    badges: ['Hackathon 1st Place', 'Digital Art Spotlight'],
    status: 'active',
    password: 'StudentLiam2026!',
    createdAt: '2025-09-15T10:00:00Z',
    lastLoginAt: '2026-09-29T20:20:00Z'
  },
  {
    id: 'user-aaliyah',
    email: 'aaliyah.patel@stjude.edu',
    name: 'Aaliyah Patel',
    username: 'aaliyah_dance',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    schoolId: 'school-st-jude',
    schoolName: 'St. Jude Creative Arts Academy',
    grade: 'Grade 12 · Senior',
    bio: 'Contemporary & fusion dancer. Dance Club President. Preparing senior graduation choreography.',
    talents: ['Contemporary Dance', 'Choreography', 'Ballet'],
    followersCount: 415,
    followingCount: 160,
    badges: ['Dance Captain', 'Choreographer of the Year'],
    status: 'active',
    password: 'StudentAaliyah2026!',
    createdAt: '2024-09-01T08:00:00Z',
    lastLoginAt: '2026-09-29T18:00:00Z'
  },
  {
    id: 'user-leo',
    email: 'leo.kim@stjude.edu',
    name: 'Leo Kim',
    username: 'leokim_spoken',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    schoolId: 'school-st-jude',
    schoolName: 'St. Jude Creative Arts Academy',
    grade: 'Grade 11 · Junior',
    bio: 'Spoken word poet, monologue actor, and school literary journal editor. Turning raw stories into rhythmic words.',
    talents: ['Poetry', 'Spoken Word', 'Drama'],
    followersCount: 220,
    followingCount: 88,
    badges: ['Poetry Slam Champion', 'Literary Editor'],
    status: 'active',
    password: 'StudentLeo2026!',
    createdAt: '2025-09-02T12:00:00Z',
    lastLoginAt: '2026-09-28T22:30:00Z'
  }
];

export const INITIAL_SONGS: Song[] = [
  {
    id: 'song-1',
    title: 'Golden Hour Echoes',
    artistId: 'user-maya',
    artistName: 'Maya Lin',
    artistAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    albumTitle: 'Hallway Harmonics EP',
    coverArt: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    duration: 194,
    genre: 'Indie Acoustic',
    audioToneType: 'synth-acoustic',
    playsCount: 1840,
    likesCount: 312,
    lyrics: "Sunlight hitting the locker row, chords I wrote three weeks ago...\nEchoes down the quiet hall, we stand tall.",
    releaseDate: '2026-02-14',
  },
  {
    id: 'song-2',
    title: 'Algorithm Sunrise',
    artistId: 'user-liam',
    artistName: 'Liam Vance ft. Jordan Blake',
    artistAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    albumTitle: 'Late Night Compiles',
    coverArt: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    duration: 215,
    genre: 'Lo-Fi Chill & Synth',
    audioToneType: 'synth-lofi',
    playsCount: 2420,
    likesCount: 429,
    lyrics: "Loops in terminal screen, sweetest sound I've ever seen.",
    releaseDate: '2026-01-20',
  },
  {
    id: 'song-3',
    title: 'Sanctuary of Voices',
    artistId: 'choir-horizon',
    artistName: 'The Horizon Chamber Choir',
    artistAvatar: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400&auto=format&fit=crop&q=80',
    albumTitle: 'Annual Spring Chorale 2026',
    coverArt: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
    duration: 242,
    genre: 'Choral / Classical',
    audioToneType: 'synth-choir',
    playsCount: 3105,
    likesCount: 567,
    isSchoolChoir: true,
    choirName: 'Horizon Chamber Choir',
    lyrics: "Voices rising like mist in the morning air, harmonies woven everywhere.",
    releaseDate: '2026-03-01',
  },
  {
    id: 'song-4',
    title: 'Neon Heartbeat',
    artistId: 'user-maya',
    artistName: 'Maya Lin',
    artistAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    albumTitle: 'Hallway Harmonics EP',
    coverArt: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    duration: 182,
    genre: 'Dream Pop',
    audioToneType: 'synth-ambient',
    playsCount: 1450,
    likesCount: 280,
    releaseDate: '2026-02-28',
  },
  {
    id: 'song-5',
    title: 'Pulse of the Stage',
    artistId: 'user-aaliyah',
    artistName: 'Aaliyah Patel (Dance Score)',
    artistAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    coverArt: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    duration: 205,
    genre: 'Rhythmic Dance Beats',
    audioToneType: 'synth-beat',
    playsCount: 980,
    likesCount: 195,
    releaseDate: '2026-03-10',
  }
];

export const INITIAL_TALENTS: TalentItem[] = [
  {
    id: 'talent-1',
    userId: 'user-aaliyah',
    studentName: 'Aaliyah Patel',
    studentUsername: 'aaliyah_dance',
    studentAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    studentGrade: 'Grade 12 · Senior',
    title: 'Gravity Defiance: Contemporary Solo',
    category: 'dance',
    description: 'An exploration of momentum and emotional tension set to minimalist string quartets. Created for the Regional Showcase.',
    mediaUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    skills: ['Contemporary', 'Improvisation', 'Choreography', 'Floorwork'],
    achievements: ['Regional Solo 1st Place', 'School Arts Council Merit Award'],
    yearsExperience: 8,
    schoolRecognition: 'Selected to open the Spring Arts Gala 2026',
    likesCount: 382,
    viewsCount: 1420,
    featured: true,
    createdAt: '2026-03-05T14:00:00Z',
  },
  {
    id: 'talent-2',
    userId: 'user-leo',
    studentName: 'Leo Kim',
    studentUsername: 'leokim_spoken',
    studentAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    studentGrade: 'Grade 11 · Junior',
    title: 'Clockwork Generation (Spoken Word Poem)',
    category: 'poetry',
    description: 'A rhythmic slam piece on digital time, student burnout, and finding genuine stillness in a world of notifications.',
    mediaUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    skills: ['Spoken Word', 'Metaphor Crafting', 'Voice Projection', 'Rhythm'],
    achievements: ['District Poetry Slam Champion 2025', 'Published in Quill & Ink'],
    yearsExperience: 4,
    schoolRecognition: 'Keynote Performer at Literary Week 2026',
    likesCount: 295,
    viewsCount: 980,
    featured: true,
    createdAt: '2026-03-08T16:30:00Z',
  },
  {
    id: 'talent-3',
    userId: 'user-liam',
    studentName: 'Liam Vance',
    studentUsername: 'liam_codes_art',
    studentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    studentGrade: 'Grade 10 · Sophomore',
    title: 'The Neural Greenhouse (Digital Canvas & Code)',
    category: 'art',
    description: 'Interactive generative art coded in WebGL and GLSL shaders that responds to ambient microphone frequencies in real time.',
    mediaUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    skills: ['Three.js', 'Shader Programming', 'Digital Illustration', 'UI/UX'],
    achievements: ['STEM + Arts Dual Innovation Prize', 'School Tech Lead'],
    yearsExperience: 3,
    schoolRecognition: 'Permanent installation in the School Media Library',
    likesCount: 412,
    viewsCount: 1680,
    featured: true,
    createdAt: '2026-03-12T11:15:00Z',
  },
  {
    id: 'talent-4',
    userId: 'user-maya',
    studentName: 'Maya Lin',
    studentUsername: 'mayalin_music',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    studentGrade: 'Grade 11 · Junior',
    title: 'Acoustic Soul Sessions & Multi-Track Vocals',
    category: 'music',
    description: 'Live acoustic loop pedal sessions with layered three-part vocal harmonies and warm fingerstyle guitar.',
    mediaUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    mediaType: 'audio',
    skills: ['Vocals', 'Acoustic Guitar', 'Loop Station', 'Logic Pro'],
    achievements: ['State Soloist Gold', 'Battle of the Bands Best Original'],
    yearsExperience: 6,
    schoolRecognition: 'Featured Soloist in Spring Orchestra Gala',
    likesCount: 468,
    viewsCount: 2100,
    featured: true,
    createdAt: '2026-03-01T09:00:00Z',
  }
];

export const INITIAL_EVENTS: SchoolEvent[] = [
  {
    id: 'event-clash-2026',
    title: 'Annual Inter-House Music Clash 2026',
    type: 'competition',
    category: 'music',
    description: 'The defining musical tournament of the year! Houses compete across Bands, Choirs, Solos, and Original Songwriting. Audience and jury voting decides the winner.',
    date: 'April 18, 2026',
    time: '6:00 PM – 9:30 PM',
    venue: 'St. Jude Grand Auditorium',
    coverImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80',
    organizerName: 'Mr. David Sterling',
    organizerRole: 'teacher',
    status: 'upcoming',
    registrationOpen: true,
    registeredCount: 38,
    capacity: 50,
    votingOpen: true,
    votingDeadline: 'April 18, 2026 9:00 PM',
    judges: ['Mr. David Sterling', 'Dr. Sarah Vance', 'Guest Producer Marcus Cole'],
    rules: [
      'Original or covered works must not exceed 5 minutes per slot',
      'All performers must be enrolled students in good academic standing',
      'Live instruments prioritized; backing tracks must be submitted by April 12'
    ],
    announcements: [
      'Audition schedule posted! Sound checks begin at 2:00 PM on show day.',
      'Public voting will open on Vibra during the live broadcast!'
    ]
  },
  {
    id: 'event-monologues',
    title: 'Spring Shakespeare & Contemporary Auditions',
    type: 'audition',
    category: 'drama',
    description: 'Open casting call for the 2026 Spring Play production. Roles available for 14 actors, stage managers, and lighting technicians.',
    date: 'April 06, 2026',
    time: '3:30 PM – 6:30 PM',
    venue: 'Black Box Drama Theatre',
    coverImage: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800&auto=format&fit=crop&q=80',
    organizerName: 'Ms. Clara Thorne (Drama Dept)',
    organizerRole: 'teacher',
    status: 'upcoming',
    registrationOpen: true,
    registeredCount: 19,
    capacity: 30,
    eligibility: 'Open to Grades 9 through 12. Monologue scripts available in room 204.',
    rules: [
      'Prepare one 90-second monologue (classical or modern)',
      'Cold reading packet will be provided at check-in'
    ],
    announcements: [
      'Callbacks will be announced on Vibra on April 8th.'
    ]
  },
  {
    id: 'event-hackathon',
    title: 'Creative Codefest: Interactive Sound & Shaders',
    type: 'competition',
    category: 'coding',
    description: 'A 24-hour creative coding jam where students build interactive web visualizers, micro-games, or digital music synthesizers.',
    date: 'April 25, 2026',
    time: '9:00 AM – Next Day 12:00 PM',
    venue: 'STEM Innovation Hub & Online',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    organizerName: 'Dr. Sarah Vance',
    organizerRole: 'admin',
    status: 'upcoming',
    registrationOpen: true,
    registeredCount: 24,
    capacity: 40,
    rules: [
      'Teams of 1 to 3 students',
      'All code must be open source and written during the hackathon window',
      'Projects must feature an artistic or musical element'
    ],
    announcements: [
      'Prizes include mentorship from local indie game studios & studio recording time!'
    ]
  }
];

export const INITIAL_CHOIRS: Choir[] = [
  {
    id: 'choir-horizon',
    name: 'The Horizon Chamber Choir',
    leadDirector: 'Mr. David Sterling',
    memberCount: 42,
    coverArt: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=600&auto=format&fit=crop&q=80',
    description: 'Premier auditioned choral ensemble representing St. Jude Academy at state festivals and community celebrations.',
    rehearsalSchedule: 'Tuesdays & Thursdays · 3:45 PM – 5:15 PM in Choir Room',
    achievements: ['State Championship Sweepstakes Trophy (2024, 2025)', 'Carnegie Hall Youth Choral Invitation'],
    songIds: ['song-3']
  },
  {
    id: 'choir-harmony',
    name: 'The Vocal Synergy A Cappella',
    leadDirector: 'Maya Lin (Student Director)',
    memberCount: 14,
    coverArt: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
    description: 'Student-run contemporary a cappella group arranging modern indie, pop, and jazz favorites with rich beatboxing.',
    rehearsalSchedule: 'Mondays & Wednesdays · 4:00 PM – 5:30 PM',
    achievements: ['Best Vocal Arrangement at High School A Cappella Cup'],
    songIds: ['song-1']
  }
];

export const INITIAL_PODCASTS: Podcast[] = [
  {
    id: 'podcast-quadcast',
    title: 'The Quadcast: Voices of St. Jude',
    hostName: 'Leo Kim & Maya Lin',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    coverArt: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80',
    description: 'Weekly student talk show diving into campus talent, behind-the-scenes rehearsal drama, and creative breakthroughs.',
    episodeCount: 14,
    latestEpisodeTitle: 'Episode 14: Overcoming Stage Fright & The 2026 Music Clash Preview',
    category: 'Student Life & Creativity'
  },
  {
    id: 'podcast-code-canvas',
    title: 'Code & Canvas',
    hostName: 'Liam Vance',
    hostAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    coverArt: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80',
    description: 'Exploring the intersection of coding, electronic music, and generative art in school creative projects.',
    episodeCount: 8,
    latestEpisodeTitle: 'Episode 8: How WebGL Shaders Make Music Look Alive',
    category: 'Tech & Art'
  }
];

export const INITIAL_POSTS: CommunityPost[] = [
  {
    id: 'post-1',
    authorId: 'user-maya',
    authorName: 'Maya Lin',
    authorUsername: 'mayalin_music',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    authorRole: 'student',
    content: "Just finished recording the acoustic demos for our track 'Golden Hour Echoes'! Massive thank you to @liam_codes_art for the cover artwork design. Can't wait for the Music Clash next month! 🎸✨",
    categoryTag: 'Music Release',
    mediaUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    mediaType: 'image',
    likesCount: 64,
    commentsCount: 12,
    isLikedByCurrentUser: false,
    createdAt: '2026-03-28T16:20:00Z',
    status: 'approved'
  },
  {
    id: 'post-2',
    authorId: 'user-aaliyah',
    authorName: 'Aaliyah Patel',
    authorUsername: 'aaliyah_dance',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    authorRole: 'student',
    content: "Dance troupe rehearsals in the studio today! We are testing the lighting cues for 'Gravity Defiance'. Anyone looking to collaborate on music for our senior graduation piece, DM me!",
    categoryTag: 'Collaboration Call',
    likesCount: 48,
    commentsCount: 7,
    isLikedByCurrentUser: false,
    createdAt: '2026-03-27T18:45:00Z',
    status: 'approved'
  },
  {
    id: 'post-3',
    authorId: 'user-teacher-sterling',
    authorName: 'Mr. David Sterling',
    authorUsername: 'sterling_arts',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
    authorRole: 'teacher',
    content: "Reminder to all choir and solo entrants: Music Clash rehearsal slots are filling up. Make sure your sheet music and backing tracks are submitted through the event portal by Friday.",
    categoryTag: 'School Announcement',
    likesCount: 89,
    commentsCount: 5,
    isLikedByCurrentUser: true,
    createdAt: '2026-03-26T10:15:00Z',
    status: 'approved'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-maya',
    title: 'Competition Voting Open',
    message: 'Voting is now active for the Annual Inter-House Music Clash 2026! Cast your vote for your peers.',
    type: 'competition',
    isRead: false,
    timestamp: '15m ago',
    linkUrl: '#events'
  },
  {
    id: 'notif-2',
    userId: 'user-maya',
    title: 'New Like on Your Song',
    message: 'Liam Vance and 14 others liked your track "Golden Hour Echoes".',
    type: 'like',
    isRead: false,
    timestamp: '2h ago',
    linkUrl: '#music'
  },
  {
    id: 'notif-3',
    userId: 'user-maya',
    title: 'Audition Call Reminder',
    message: 'Spring Shakespeare & Contemporary Auditions registration closes this Friday.',
    type: 'audition',
    isRead: true,
    timestamp: '1d ago',
    linkUrl: '#events'
  }
];

export const INITIAL_VIDEOS: TalentVideo[] = [
  {
    id: 'vid-maya-1',
    studentId: 'user-maya',
    studentName: 'Maya Lin',
    studentUsername: 'mayalin_music',
    studentAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    studentGrade: 'Grade 11 · Junior',
    schoolName: 'St. Jude Creative Arts Academy',
    title: 'Acoustic Hallway Session: "Golden Hour Echoes"',
    caption: 'Testing the natural reverb in the North Wing stairwell between 4th and 5th period 🎸 Finalizing this arrangement for the Annual Inter-House Music Clash! Drop feedback below! ✨',
    tags: ['#MusicClash2026', '#VocalSolo', '#IndieAcoustic', '#StJudeTalent'],
    category: 'music',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-playing-an-acoustic-guitar-at-home-43224-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    audioTitle: 'Golden Hour Echoes (Acoustic Solo)',
    audioArtist: 'Maya Lin · St. Jude Choral Soloist',
    audioToneType: 'synth-acoustic',
    likesCount: 1248,
    commentsCount: 84,
    sharesCount: 192,
    savesCount: 310,
    isLiked: false,
    isSaved: false,
    isFollowing: false,
    competitionTag: 'Annual Inter-House Music Clash 2026',
    comments: [
      {
        id: 'c-1',
        userId: 'user-liam',
        userName: 'Liam Vance',
        userAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
        userGrade: 'Grade 10 · Sophomore',
        text: 'That chord transition at 0:22 gave me goosebumps! St. Jude is definitely bringing the trophy home 🔥',
        timestamp: '2h ago',
        likesCount: 34
      },
      {
        id: 'c-2',
        userId: 'user-teacher-sterling',
        userName: 'Mr. David Sterling',
        userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
        userGrade: 'Faculty · Head of Performing Arts',
        text: 'Superb breath control, Maya. Make sure to project slightly more in the final modulation for auditorium acoustics.',
        timestamp: '4h ago',
        likesCount: 68
      },
      {
        id: 'c-3',
        userId: 'user-aaliyah',
        userName: 'Aaliyah Patel',
        userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
        userGrade: 'Grade 12 · Senior',
        text: 'Can our dance troupe choreograph a piece to this track? Sending you a DM right now! 💃',
        timestamp: '5h ago',
        likesCount: 19
      }
    ],
    createdAt: '2026-03-29T14:20:00Z'
  },
  {
    id: 'vid-aaliyah-1',
    studentId: 'user-aaliyah',
    studentName: 'Aaliyah Patel',
    studentUsername: 'aaliyah_dance',
    studentAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    studentGrade: 'Grade 12 · Senior',
    schoolName: 'St. Jude Creative Arts Academy',
    title: 'Gravity Defiance · Senior Contemporary Solo',
    caption: 'Studio rehearsal before the Spring Showcase! Exploring weight, momentum, and finding stillness mid-air. Dedicated to our graduation class 🤍🩰',
    tags: ['#ContemporaryDance', '#DanceTroupe', '#SeniorProject', '#SpringGala'],
    category: 'dance',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-dancing-in-a-dance-studio-41132-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    audioTitle: 'Pulse of the Stage (Contemporary Score)',
    audioArtist: 'Aaliyah Patel & Studio Strings',
    audioToneType: 'synth-beat',
    likesCount: 1890,
    commentsCount: 112,
    sharesCount: 340,
    savesCount: 520,
    isLiked: false,
    isSaved: false,
    isFollowing: true,
    auditionTag: 'Spring Showcase Auditions',
    comments: [
      {
        id: 'c-4',
        userId: 'user-leo',
        userName: 'Leo Kim',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
        userGrade: 'Grade 11 · Junior',
        text: 'The fluidity of that drop into the floor recovery was poetry in motion! Pure art.',
        timestamp: '1h ago',
        likesCount: 22
      },
      {
        id: 'c-5',
        userId: 'user-admin-vance',
        userName: 'Dr. Sarah Vance',
        userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
        userGrade: 'Administration · Principal',
        text: 'Exceptional dedication to your craft, Aaliyah. A stellar representative of our fine arts department.',
        timestamp: '3h ago',
        likesCount: 45
      }
    ],
    createdAt: '2026-03-29T10:15:00Z'
  },
  {
    id: 'vid-liam-1',
    studentId: 'user-liam',
    studentName: 'Liam Vance',
    studentUsername: 'liam_codes_art',
    studentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    studentGrade: 'Grade 10 · Sophomore',
    schoolName: 'St. Jude Creative Arts Academy',
    title: 'Generative Audio Shader · WebGL Sound Reactive Tunnel',
    caption: 'Our 24-hr Creative Codefest submission! Coded this GLSL shader tunnel that reacts in real-time to student microphone frequencies. Open source repo in bio 💻🌌',
    tags: ['#CreativeCoding', '#WebGL', '#GLSL', '#HackTheSchool'],
    category: 'coding',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-typing-on-a-laptop-keyboard-41147-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    audioTitle: 'Algorithm Sunrise (Generative Synth)',
    audioArtist: 'Liam Vance ft. Jordan Blake',
    audioToneType: 'synth-lofi',
    likesCount: 940,
    commentsCount: 65,
    sharesCount: 145,
    savesCount: 270,
    isLiked: false,
    isSaved: false,
    isFollowing: false,
    competitionTag: 'Creative Codefest: Sound & Shaders',
    comments: [
      {
        id: 'c-6',
        userId: 'user-maya',
        userName: 'Maya Lin',
        userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
        userGrade: 'Grade 11 · Junior',
        text: 'Can we use this visualizer on the auditorium LED wall during our choir set?! Looks unreal!',
        timestamp: '3h ago',
        likesCount: 31
      }
    ],
    createdAt: '2026-03-28T18:40:00Z'
  },
  {
    id: 'vid-leo-1',
    studentId: 'user-leo',
    studentName: 'Leo Kim',
    studentUsername: 'leokim_spoken',
    studentAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    studentGrade: 'Grade 11 · Junior',
    schoolName: 'St. Jude Creative Arts Academy',
    title: 'Clockwork Generation · Live Spoken Word Poetry',
    caption: 'First live stage test for the District Poetry Slam. A piece about breaking free from algorithm timers and finding real student community. Let me know what hit home 🎙️',
    tags: ['#PoetrySlam', '#SpokenWord', '#LiteraryArts', '#StudentVoices'],
    category: 'poetry',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-man-performing-a-monologue-on-stage-43572-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80',
    audioTitle: 'Clockwork Silence (Ambient Monologue)',
    audioArtist: 'Leo Kim · Literary Slam Champion',
    audioToneType: 'synth-ambient',
    likesCount: 1120,
    commentsCount: 96,
    sharesCount: 210,
    savesCount: 380,
    isLiked: false,
    isSaved: false,
    isFollowing: false,
    auditionTag: 'Spring Monologue Showcase',
    comments: [
      {
        id: 'c-7',
        userId: 'user-aaliyah',
        userName: 'Aaliyah Patel',
        userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
        userGrade: 'Grade 12 · Senior',
        text: '"We trade our heartbeats for status pings" — that line resonated so deeply Leo! 👏',
        timestamp: '4h ago',
        likesCount: 29
      }
    ],
    createdAt: '2026-03-27T12:00:00Z'
  },
  {
    id: 'vid-choir-1',
    studentId: 'choir-horizon',
    studentName: 'Horizon Chamber Choir',
    studentUsername: 'horizon_choir',
    studentAvatar: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400&auto=format&fit=crop&q=80',
    studentGrade: 'Ensemble · 42 Vocalists',
    schoolName: 'St. Jude Creative Arts Academy',
    title: 'Sanctuary of Voices · 4-Part Harmonic Cadence',
    caption: 'Full chamber ensemble rehearsal in the Grand Auditorium! 42 student voices weaving polyphonic counterpoints under Mr. Sterling\'s baton. Preparing for state championship 🎶',
    tags: ['#SchoolChoir', '#ChoralHarmonies', '#StateChampionship', '#StJudeVoices'],
    category: 'choir',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-choir-singing-together-42845-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop&q=80',
    audioTitle: 'Sanctuary of Voices (Choral Harmony)',
    audioArtist: 'The Horizon Chamber Choir',
    audioToneType: 'synth-choir',
    likesCount: 2450,
    commentsCount: 140,
    sharesCount: 480,
    savesCount: 710,
    isLiked: false,
    isSaved: false,
    isFollowing: true,
    competitionTag: 'Annual Inter-House Music Clash 2026',
    comments: [
      {
        id: 'c-8',
        userId: 'user-teacher-sterling',
        userName: 'Mr. David Sterling',
        userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
        userGrade: 'Faculty · Head of Performing Arts',
        text: 'Proud of each and every section today. Remember Saturday masterclass rehearsal at 10 AM sharp!',
        timestamp: '1d ago',
        likesCount: 52
      }
    ],
    createdAt: '2026-03-26T16:00:00Z'
  },
  {
    id: 'vid-elena-1',
    studentId: 'user-elena',
    studentName: 'Elena Cruz',
    studentUsername: 'elena_sketches',
    studentAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    studentGrade: 'Grade 10 · Sophomore',
    schoolName: 'St. Jude Creative Arts Academy',
    title: 'Cyberpunk School Falcon Mascot · 4-Hour Time-Lapse',
    caption: 'Designed our school falcon mascot reimagined as a neon cyberpunk guardian! 30-sec time-lapse in Procreate 🦅🎨 Voting is live for the Spirit Week banner!',
    tags: ['#DigitalArt', '#SpeedPaint', '#Procreate', '#SchoolSpirit'],
    category: 'art',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-artist-painting-on-a-digital-tablet-41223-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=800&auto=format&fit=crop&q=80',
    audioTitle: 'Neon Heartbeat (Art Score)',
    audioArtist: 'Elena Cruz & Maya Lin',
    audioToneType: 'synth-lofi',
    likesCount: 880,
    commentsCount: 53,
    sharesCount: 110,
    savesCount: 195,
    isLiked: false,
    isSaved: false,
    isFollowing: false,
    competitionTag: 'Spirit Week Digital Mascot Banner Contest',
    comments: [
      {
        id: 'c-9',
        userId: 'user-liam',
        userName: 'Liam Vance',
        userAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
        userGrade: 'Grade 10 · Sophomore',
        text: 'The color palette with that teal and magenta backlight is pristine Elena! 10/10.',
        timestamp: '1d ago',
        likesCount: 18
      }
    ],
    createdAt: '2026-03-25T11:30:00Z'
  }
];

export const INITIAL_SETTINGS: PlatformSettings = {
  schoolName: 'St. Jude Creative Arts Academy',
  academicYear: '2025-2026 (Spring Semester)',
  allowStudentUploads: true,
  requireContentApproval: false,
  votingEnabledGlobally: true,
  maxVideoUploadSizeMb: 150,
  notifyAdminsOnReport: true,
  allowGuestPreview: true,
};

export const INITIAL_REPORTS: ReportItem[] = [
  {
    id: 'rep-1',
    reporterId: 'user-leo',
    reporterName: 'Leo Kim',
    targetType: 'post',
    targetId: 'post-1',
    targetTitle: 'Stairwell Acoustic Session Post',
    targetAuthorName: 'Maya Lin',
    reason: 'Audio distortion test issue or question regarding copyright permission.',
    status: 'pending',
    createdAt: '2026-03-29T15:00:00Z'
  },
  {
    id: 'rep-2',
    reporterId: 'user-aaliyah',
    reporterName: 'Aaliyah Patel',
    targetType: 'comment',
    targetId: 'c-99',
    targetTitle: 'Auditorium Rehearsal Comment',
    targetAuthorName: 'Anonymous Peer',
    reason: 'Mild spam / promotional message about outside dance gear.',
    status: 'resolved',
    actionTaken: 'Comment removed and user issued moderation reminder.',
    createdAt: '2026-03-28T09:30:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-09-30T02:30:12Z',
    adminId: 'user-superadmin',
    adminName: 'Marcus Thorne',
    adminRole: 'superadmin',
    action: 'ADMIN_LOGIN',
    resource: 'Auth: Session Created',
    status: 'success',
    ipAddress: '192.168.1.104',
    details: 'Authenticated via secure 2FA token'
  },
  {
    id: 'log-2',
    timestamp: '2026-09-30T01:45:00Z',
    adminId: 'user-admin-vance',
    adminName: 'Dr. Sarah Vance',
    adminRole: 'admin',
    action: 'SETTINGS_UPDATE',
    resource: 'Platform: Voting Governance',
    status: 'success',
    ipAddress: '10.0.4.22',
    details: 'Opened audience ballot for Annual Inter-House Music Clash 2026'
  },
  {
    id: 'log-3',
    timestamp: '2026-09-29T19:12:00Z',
    adminId: 'user-teacher-sterling',
    adminName: 'Mr. David Sterling',
    adminRole: 'teacher',
    action: 'CONTENT_APPROVE',
    resource: 'Song: "Sanctuary of Voices"',
    status: 'success',
    ipAddress: '10.0.4.58',
    details: 'Chamber choir official festival recording approved for streaming'
  },
  {
    id: 'log-4',
    timestamp: '2026-09-29T14:05:00Z',
    adminId: 'user-admin-vance',
    adminName: 'Dr. Sarah Vance',
    adminRole: 'admin',
    action: 'USER_ROLE_CHANGE',
    resource: 'User: Mr. David Sterling',
    status: 'success',
    ipAddress: '10.0.4.22',
    details: 'Role updated to Faculty Patron with event approval privileges'
  },
  {
    id: 'log-5',
    timestamp: '2026-09-29T11:20:00Z',
    adminId: 'user-admin-vance',
    adminName: 'Dr. Sarah Vance',
    adminRole: 'admin',
    action: 'MODERATION_RESOLVE',
    resource: 'Report: #rep-2',
    status: 'success',
    ipAddress: '10.0.4.22',
    details: 'Spam comment dismissed and removed from dance showcase'
  },
  {
    id: 'log-6',
    timestamp: '2026-09-28T16:40:00Z',
    adminId: 'user-superadmin',
    adminName: 'Marcus Thorne',
    adminRole: 'superadmin',
    action: 'STORAGE_HEALTH_CHECK',
    resource: 'Cloud Buckets: /videos, /songs',
    status: 'success',
    ipAddress: '192.168.1.104',
    details: 'Storage integrity verified: 4.8 GB allocated, 0 orphaned objects'
  }
];


